apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
        - name: task-service
          image: fsd-project-task-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mariadb://mysql:3306/taskdb
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: "123"
---
apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30002
  selector:
    app: task-service